# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: d236b77108a0d0275215579bbc3fe51b8a2c00443a48f21b988535a00c50e08f8f98169184da6b70f5e2fca275572120e99e7a39c449cd8962f38d8eda2290de

test:
  secret_key_base: 03ce7c94906c3be6f81acfa3ea4a99e066f65e0a8b38b2fe7cbc37921987c2b453d0a394a4781bdd2b454d5f1d0e1151d395546428d0074bdef9ee56f7e0954c

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
